import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :messaging_service, MessagingServiceWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: MessagingService.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Configure webhook authentication for production
# Use environment variables for security
config :messaging_service, :webhook_auth,
  bearer_tokens:
    System.get_env("WEBHOOK_BEARER_TOKENS", "") |> String.split(",") |> Enum.reject(&(&1 == "")),
  api_keys:
    System.get_env("WEBHOOK_API_KEYS", "") |> String.split(",") |> Enum.reject(&(&1 == "")),
  basic_auth:
    [
      {System.get_env("WEBHOOK_USERNAME"), System.get_env("WEBHOOK_PASSWORD")}
    ]
    |> Enum.reject(fn {u, p} -> is_nil(u) or is_nil(p) end)
